#!/bin/sh
# The script creates a deb packet for the Kirawnik project.

umask 0022


OUTPUT_FILE=$1
DEB_DIR="deb-kirawnik"

if [ -z $1 ] ; then
	OUTPUT_FILE="kirawnik.deb"
fi

if [ -d $DEB_DIR -o -f $DEB_DIR ] ; then
	rm -rf $DEB_DIR
fi

mkdir --mode=755 $DEB_DIR
cd $DEB_DIR

mkdir --mode=755 usr usr/bin usr/lib usr/share

cp ../../bin/kirawnik usr/bin
cp -r ../../lib/* usr/lib/
cp -r ../../share/* usr/share
cp -r ../DEBIAN .

find usr/ -name \.gitignore | xargs rm -f

find . -type d | xargs chmod 755
find . -type f | xargs chmod 644
find . -type f -a -name "kirawnik" | xargs chmod 755
find . -type f -a -name "postinst" | xargs chmod 755

md5deep -rl -o f usr > DEBIAN/md5sums

cd ..
fakeroot dpkg-deb --build $DEB_DIR $OUTPUT_FILE

